# Additive-Polymer Family Compatibility Matrix
# Simple n_additives x n_families compatibility parameters
# Values range from 0.0 (no compatibility) to 1.0 (full compatibility)
# This replaces the complex pairwise compatibility system

# Polymer families
polymer_families:
  - PLA
  - PBAT  
  - PHB
  - PHA
  - PBS
  - PCL
  - Bio-PE
  - LDPE
  - PP
  - PET
  - PVDC
  - PA
  - EVOH

# Additive compatibility with each polymer family
additive_compatibility:
  Glycerol:       # Plasticizer additive
    PLA: 0.8      # Good compatibility with PLA (plasticizer effect)
    PBAT: 0.9     # Excellent compatibility with PBAT (flexible polymer)
    PHB: 0.6      # Moderate compatibility with PHB
    PHA: 0.7      # Good compatibility with PHA
    PBS: 0.8      # Good compatibility with PBS
    PCL: 0.9      # Excellent compatibility with PCL (flexible)
    Bio-PE: 0.5   # Moderate compatibility with Bio-PE
    LDPE: 0.6     # Moderate compatibility with LDPE
    PP: 0.4       # Lower compatibility with PP (crystalline)
    PET: 0.3      # Low compatibility with PET (crystalline)
    PVDC: 0.2     # Very low compatibility with PVDC (barrier polymer)
    PA: 0.5       # Moderate compatibility with PA
    EVOH: 0.4     # Lower compatibility with EVOH (barrier polymer)
  

