# Per-property weights for UMM3 corrections
# wT: strength of that property overall (uses property-specific K parameters), wI: interface interaction weight (uses pairwise compatibility)
# Property-specific K parameters: K_ts, K_wvtr, K_eab, K_cobb, K_adhesion, K_compost, K_otr
weights:
  tensile:    { wT:  1.00, wI:  1.00}  # Uses K_ts
  elongation: { wT:  1.00, wI:  1.00}  # Uses K_eab
  otr:        { wT: -1.00, wI: -1.00}  # Uses K_otr
  wvtr:       { wT: -1.00, wI: -1.00}  # Uses K_wvtr
  seal:       { wT:  1.00, wI:  1.00}  # Uses K_seal
  cobb:       { wT: -1.00, wI:  1.00}  # Uses K_cobb
  compost:    { wT:  1.00, wI:  1.00}  # Uses K_compost
