# WVTR Material Family Compatibility Matrix
# Controls interfacial compatibility for Water Vapor Transmission Rate
# Barrier properties are highly sensitive to phase separation
# KI values: 0.0 = perfect compatibility, 1.0+ = complete immiscibility

material_family_compatibility:
  # PLA interactions (row 1)
  "PLA-PHB": {KI: 0.0, description: "PLA-PHB: Poor compatibility, phase separation"}
  "PLA-PHAa": {KI: 0.0, description: "PLA-PHAa: Moderate compatibility"}
  "PLA-PHAs": {KI: 0.0, description: "PLA-PHAs: Moderate compatibility"}
  "PLA-PGA": {KI: 0.0, description: "PLA-PGA: Good compatibility (similar structure)"}
  "PLA-PBAT": {KI: -1.402, description: "PLA-PBAT: Optimized compatibility (iteration 50)"}
  "PLA-PBS": {KI: 0.0, description: "PLA-PBS: Moderate compatibility"}
  "PLA-PBSA": {KI: 0.0, description: "PLA-PBSA: Moderate compatibility"}
  "PLA-PCL": {KI: 0.0, description: "PLA-PCL: Moderate compatibility"}
  "PLA-Bio-PE": {KI: 2.551, description: "PLA-Bio-PE: Optimized compatibility (iteration 50)"}
  "PLA-LDPE": {KI: 0.0, description: "PLA-LDPE: Poor compatibility"}
  "PLA-PP": {KI: 0.0, description: "PLA-PP: Very poor compatibility, immiscible"}
  "PLA-PET": {KI: 0.0, description: "PLA-PET: Poor compatibility"}
  "PLA-PVDC": {KI: 0.0, description: "PLA-PVDC: Very poor compatibility"}
  "PLA-PA": {KI: 0.0, description: "PLA-PA: Moderate compatibility"}
  "PLA-EVOH": {KI: 0.0, description: "PLA-EVOH: Moderate compatibility"}
  "PLA-PHBH": {KI: 0.0, description: "PLA-PHBH: Moderate compatibility"}
  
  # PHB interactions (row 2)
  "PHB-PHAa": {KI: 0.0, description: "PHB-PHAa: Good compatibility (similar structure)"}
  "PHB-PHAs": {KI: 0.0, description: "PHB-PHAs: Good compatibility (similar structure)"}
  "PHB-PGA": {KI: 0.0, description: "PHB-PGA: Moderate compatibility"}
  "PHB-PBAT": {KI: 0.0, description: "PHB-PBAT: Bad compatibility"}
  "PHB-PBS": {KI: 0.0, description: "PHB-PBS: Good compatibility"}
  "PHB-PBSA": {KI: 0.0, description: "PHB-PBSA: Moderate compatibility"}
  "PHB-PCL": {KI: 0.0, description: "PHB-PCL: Moderate compatibility"}
  "PHB-Bio-PE": {KI: 0.0, description: "PHB-Bio-PE: Poor compatibility"}
  "PHB-LDPE": {KI: 0.0, description: "PHB-LDPE: Poor compatibility"}
  "PHB-PP": {KI: 0.0, description: "PHB-PP: Poor compatibility"}
  "PHB-PET": {KI: 0.0, description: "PHB-PET: Moderate compatibility"}
  "PHB-PVDC": {KI: 0.0, description: "PHB-PVDC: Poor compatibility"}
  "PHB-PA": {KI: 0.0, description: "PHB-PA: Moderate compatibility"}
  "PHB-EVOH": {KI: 0.0, description: "PHB-EVOH: Good compatibility"}
  "PHBV-PLA": {KI: 0.0, description: "PHBV-PLA: Good compatibility"}
  "PHBV-PHB": {KI: 0.0, description: "PHBV-PHB: Good compatibility"}
  "PHBV-PGA": {KI: 0.0, description: "PHBV-PGA: Good compatibility"}
  "PHBV-PBAT": {KI: 0.169, description: "PHBV-PBAT: Optimized compatibility (iteration 50)"}
  "PHBV-PBS": {KI: 0.0, description: "PHBV-PBS: Good compatibility"}
  "PHBV-PBSA": {KI: -1.821, description: "PHBV-PBSA: Optimized compatibility (iteration 50)"}
  "PHBV-PCL": {KI: 0.0, description: "PHBV-PCL: Good compatibility"}
  "PHBV-Bio-PE": {KI: 0.0, description: "PHBV-Bio-PE: Moderate compatibility"}
  "PHBV-LDPE": {KI: 0.0, description: "PHBV-LDPE: Moderate compatibility"}
  "PHBV-PP": {KI: 0.0, description: "PHBV-PP: Moderate compatibility"}
  "PHBV-PET": {KI: 0.0, description: "PHBV-PET: Moderate compatibility"}
  "PHBV-PVDC": {KI: 0.0, description: "PHBV-PVDC: Moderate compatibility"}
  "PHBV-PA": {KI: 0.0, description: "PHBV-PA: Moderate compatibility"}
  "PHBV-EVOH": {KI: 0.0, description: "PHBV-EVOH: Moderate compatibility"}
  "PHB-PHBH": {KI: 0.0, description: "PHB-PHBH: Good compatibility (same family)"}
  
  # PHBH interactions (row 2b)
  "PHBH-PHAa": {KI: 0.0, description: "PHBH-PHAa: Good compatibility"}
  "PHBH-PHAs": {KI: 0.0, description: "PHBH-PHAs: Good compatibility"}
  "PHBH-PGA": {KI: 0.0, description: "PHBH-PGA: Moderate compatibility"}
  "PHAs-PHBV": {KI: 0.010, description: "PHAs-PHBV: Optimized compatibility (iteration 50)"}
  "PHAs-PHAa": {KI: 0.0, description: "PHAs-PHAa: Good compatibility (same family)"}
  "PHAa-PHBV": {KI: 0.0, description: "PHAa-PHBV: Good compatibility"}
  "PHBV-PHBH": {KI: 0.0, description: "PHBV-PHBH: Good compatibility (same family)"}
  "PHBV-PHAs": {KI: -0.0, description: "PHBV-PHAs: Good compatibility"}
  "PHBV-PHAa": {KI: 0.0, description: "PHBV-PHAa: Good compatibility"}
  "PHBH-PHBV": {KI: 0.0, description: "PHBH-PHBV: Good compatibility (same family)"}
  "PHBH-PBAT": {KI: 0.0, description: "PHBH-PBAT: Bad compatibility"}
  "PHBH-PBS": {KI: 0.0, description: "PHBH-PBS: Good compatibility"}
  "PHBH-PBSA": {KI: 0.0, description: "PHBH-PBSA: Moderate compatibility"}
  "PHBH-PCL": {KI: 0.0, description: "PHBH-PCL: Moderate compatibility"}
  "PHBH-Bio-PE": {KI: 0.0, description: "PHBH-Bio-PE: Poor compatibility"}
  "PHBH-LDPE": {KI: 0.0, description: "PHBH-LDPE: Poor compatibility"}
  "PHBH-PP": {KI: 0.0, description: "PHBH-PP: Poor compatibility"}
  "PHBH-PET": {KI: 0.0, description: "PHBH-PET: Moderate compatibility"}
  "PHBH-PVDC": {KI: 0.0, description: "PHBH-PVDC: Poor compatibility"}
  "PHBH-PA": {KI: 0.0, description: "PHBH-PA: Moderate compatibility"}
  "PHBH-EVOH": {KI: 0.0, description: "PHBH-EVOH: Good compatibility"}
  
  # PHAa interactions (row 3a)
  "PHAa-PHAs": {KI: 0.0, description: "PHAa-PHAs: Good compatibility (same family)"}
  "PHAa-PGA": {KI: 0.0, description: "PHAa-PGA: Good compatibility"}
  "PHAa-PBAT": {KI: 0.0, description: "PHAa-PBAT: Good compatibility"}
  "PHAa-PBS": {KI: -0.501, description: "PHAa-PBS: Optimized compatibility (iteration 50)"}
  "PHAa-PBSA": {KI: 0.0, description: "PHAa-PBSA: Moderate compatibility"}
  "PHAa-PCL": {KI: 0.0, description: "PHAa-PCL: Good compatibility"}
  "PHAa-Bio-PE": {KI: 0.0, description: "PHAa-Bio-PE: Moderate compatibility"}
  "PHAa-LDPE": {KI: 0.0, description: "PHAa-LDPE: Moderate compatibility"}
  "PHAa-PP": {KI: 0.0, description: "PHAa-PP: Moderate compatibility"}
  "PHAa-PET": {KI: 0.0, description: "PHAa-PET: Moderate compatibility"}
  "PHAa-PVDC": {KI: 0.0, description: "PHAa-PVDC: Poor compatibility"}
  "PHAa-PA": {KI: 0.0, description: "PHAa-PA: Good compatibility"}
  "PHAa-EVOH": {KI: 0.0, description: "PHAa-EVOH: Good compatibility"}
  "PHAa-PHBH": {KI: 0.0, description: "PHAa-PHBH: Good compatibility"}
  
  # PHAs interactions (row 3b)
  "PHAs-PGA": {KI: 0.0, description: "PHAs-PGA: Good compatibility"}
  "PHAs-PBAT": {KI: 0.0, description: "PHAs-PBAT: Good compatibility"}
  "PHAs-PBS": {KI: -1.248, description: "PHAs-PBS: Optimized compatibility (iteration 50)"}
  "PHAs-PBSA": {KI: 0.0, description: "PHAs-PBSA: Moderate compatibility"}
  "PHAs-PCL": {KI: 0.0, description: "PHAs-PCL: Good compatibility"}
  "PHAs-Bio-PE": {KI: 0.0, description: "PHAs-Bio-PE: Moderate compatibility"}
  "PHAs-LDPE": {KI: 0.0, description: "PHAs-LDPE: Moderate compatibility"}
  "PHAs-PP": {KI: 0.0, description: "PHAs-PP: Moderate compatibility"}
  "PHAs-PET": {KI: 0.0, description: "PHAs-PET: Moderate compatibility"}
  "PHAs-PVDC": {KI: 0.0, description: "PHAs-PVDC: Poor compatibility"}
  "PHAs-PA": {KI: 0.0, description: "PHAs-PA: Good compatibility"}
  "PHAs-EVOH": {KI: 0.0, description: "PHAs-EVOH: Good compatibility"}
  "PHAs-PHBH": {KI: 0.0, description: "PHAs-PHBH: Good compatibility"}
  
  # PGA interactions (row 4)
  "PGA-PBAT": {KI: 0.0, description: "PGA-PBAT: Moderate compatibility"}
  "PGA-PBS": {KI: 0.0, description: "PGA-PBS: Good compatibility"}
  "PGA-PBSA": {KI: 0.0, description: "PGA-PBSA: Moderate compatibility"}
  "PGA-PCL": {KI: 0.0, description: "PGA-PCL: Good compatibility"}
  "PGA-Bio-PE": {KI: 0.0, description: "PGA-Bio-PE: Poor compatibility"}
  "PGA-LDPE": {KI: 0.0, description: "PGA-LDPE: Poor compatibility"}
  "PGA-PP": {KI: 0.0, description: "PGA-PP: Poor compatibility"}
  "PGA-PET": {KI: 0.0, description: "PGA-PET: Moderate compatibility"}
  "PGA-PVDC": {KI: 0.0, description: "PGA-PVDC: Poor compatibility"}
  "PGA-PA": {KI: 0.0, description: "PGA-PA: Moderate compatibility"}
  "PGA-EVOH": {KI: 0.0, description: "PGA-EVOH: Good compatibility"}
  
  # PBAT interactions (row 5)
  "PBAT-PBS": {KI: 0.0, description: "PBAT-PBS: Good compatibility (similar structure)"}
  "PBAT-PBSA": {KI: 0.0, description: "PBAT-PBSA: Good compatibility (similar structure)"}
  "PBAT-PCL": {KI: 0.0, description: "PBAT-PCL: Good compatibility"}
  "PBAT-Bio-PE": {KI: 0.0, description: "PBAT-Bio-PE: Moderate compatibility"}
  "PBAT-LDPE": {KI: 0.0, description: "PBAT-LDPE: Moderate compatibility"}
  "PBAT-PP": {KI: 0.0, description: "PBAT-PP: Moderate compatibility"}
  "PBAT-PET": {KI: 0.0, description: "PBAT-PET: Moderate compatibility"}
  "PBAT-PVDC": {KI: 0.0, description: "PBAT-PVDC: Poor compatibility"}
  "PBAT-PA": {KI: 0.0, description: "PBAT-PA: Good compatibility"}
  "PBAT-EVOH": {KI: 0.0, description: "PBAT-EVOH: Good compatibility"}
  
  # PBS interactions (row 6)
  "PBS-PBSA": {KI: -0.809, description: "PBS-PBSA: Optimized compatibility (iteration 50)"}
  "PBS-PCL": {KI: 0.0, description: "PBS-PCL: Good compatibility"}
  "PBS-Bio-PE": {KI: 0.0, description: "PBS-Bio-PE: Moderate compatibility"}
  "PBS-LDPE": {KI: 0.0, description: "PBS-LDPE: Moderate compatibility"}
  "PBS-PP": {KI: 0.0, description: "PBS-PP: Moderate compatibility"}
  "PBS-PET": {KI: 0.0, description: "PBS-PET: Good compatibility"}
  "PBS-PVDC": {KI: 0.0, description: "PBS-PVDC: Moderate compatibility"}
  "PBS-PA": {KI: 0.0, description: "PBS-PA: Good compatibility"}
  "PBS-EVOH": {KI: 0.0, description: "PBS-EVOH: Very good compatibility"}
  
  # PBSA interactions (row 7)
  "PBSA-PCL": {KI: 0.0, description: "PBSA-PCL: Good compatibility"}
  "PBSA-Bio-PE": {KI: 0.0, description: "PBSA-Bio-PE: Moderate compatibility"}
  "PBSA-LDPE": {KI: 0.0, description: "PBSA-LDPE: Moderate compatibility"}
  "PBSA-PP": {KI: 0.0, description: "PBSA-PP: Moderate compatibility"}
  "PBSA-PET": {KI: 0.0, description: "PBSA-PET: Good compatibility"}
  "PBSA-PVDC": {KI: 0.0, description: "PBSA-PVDC: Moderate compatibility"}
  "PBSA-PA": {KI: 0.0, description: "PBSA-PA: Good compatibility"}
  "PBSA-EVOH": {KI: 0.0, description: "PBSA-EVOH: Good compatibility"}
  
  # PCL interactions (row 8)
  "PCL-Bio-PE": {KI: 0.0, description: "PCL-Bio-PE: Moderate compatibility"}
  "PCL-LDPE": {KI: 0.0, description: "PCL-LDPE: Good compatibility"}
  "PCL-PP": {KI: 0.0, description: "PCL-PP: Moderate compatibility"}
  "PCL-PET": {KI: 0.0, description: "PCL-PET: Good compatibility"}
  "PCL-PVDC": {KI: 0.0, description: "PCL-PVDC: Moderate compatibility"}
  "PCL-PA": {KI: 0.0, description: "PCL-PA: Very good compatibility"}
  "PCL-EVOH": {KI: 0.0, description: "PCL-EVOH: Good compatibility"}
  
  # Bio-PE interactions (row 9)
  "Bio-PE-PBAT": {KI: 0.174, description: "Bio-PE-PBAT: Optimized compatibility (iteration 50)"}
  "Bio-PE-LDPE": {KI: 0.0, description: "Bio-PE-LDPE: Very good compatibility (same family)"}
  "Bio-PE-PP": {KI: 0.0, description: "Bio-PE-PP: Good compatibility"}
  "Bio-PE-PET": {KI: 0.0, description: "Bio-PE-PET: Good compatibility"}
  "Bio-PE-PVDC": {KI: 0.0, description: "Bio-PE-PVDC: Moderate compatibility"}
  "Bio-PE-PA": {KI: 0.0, description: "Bio-PE-PA: Moderate compatibility"}
  "Bio-PE-EVOH": {KI: 0.0, description: "Bio-PE-EVOH: Moderate compatibility"}
  
  # LDPE interactions (row 10)
  "LDPE-PP": {KI: 0.0, description: "LDPE-PP: Very good compatibility (same family)"}
  "LDPE-PET": {KI: 0.0, description: "LDPE-PET: Good compatibility"}
  "LDPE-PVDC": {KI: 0.0, description: "LDPE-PVDC: Good compatibility"}
  "LDPE-PA": {KI: 0.0, description: "LDPE-PA: Moderate compatibility"}
  "LDPE-EVOH": {KI: 0.0, description: "LDPE-EVOH: Moderate compatibility"}
  
  # PP interactions (row 11)
  "PP-PET": {KI: 0.0, description: "PP-PET: Good compatibility"}
  "PP-PVDC": {KI: 0.0, description: "PP-PVDC: Good compatibility"}
  "PP-PA": {KI: 0.0, description: "PP-PA: Moderate compatibility"}
  "PP-EVOH": {KI: 0.0, description: "PP-EVOH: Moderate compatibility"}
  
  # PET interactions (row 12)
  "PET-PVDC": {KI: 0.0, description: "PET-PVDC: Good compatibility"}
  "PET-PA": {KI: 0.0, description: "PET-PA: Very good compatibility"}
  "PET-EVOH": {KI: 0.0, description: "PET-EVOH: Good compatibility"}
  
  # PVDC interactions (row 13)
  "PVDC-PA": {KI: 0.0, description: "PVDC-PA: Good compatibility"}
  "PVDC-EVOH": {KI: 0.0, description: "PVDC-EVOH: Good compatibility"}
  
  # PA interactions (row 14)
  "PA-EVOH": {KI: 0.0, description: "PA-EVOH: Very good compatibility"}
  
  # Same family interactions (self-interactions)
  "PLA-PLA": {KI: 0.0, description: "PLA self-interaction - perfect compatibility"}
  "PHB-PHB": {KI: 0.0, description: "PHB self-interaction - perfect compatibility"}
  "PHAa-PHAa": {KI: 0.0, description: "PHAa self-interaction - perfect compatibility"}
  "PHAs-PHAs": {KI: 0.0, description: "PHAs self-interaction - perfect compatibility"}
  "PHBH-PHBH": {KI: 0.0, description: "PHBH self-interaction - perfect compatibility"}
  "PGA-PGA": {KI: 0.0, description: "PGA self-interaction - perfect compatibility"}
  "PBAT-PBAT": {KI: 0.0, description: "PBAT self-interaction - perfect compatibility"}
  "PBS-PBS": {KI: 0.0, description: "PBS self-interaction - perfect compatibility"}
  "PBSA-PBSA": {KI: 0.0, description: "PBSA self-interaction - perfect compatibility"}
  "PCL-PCL": {KI: 0.0, description: "PCL self-interaction - perfect compatibility"}
  "Bio-PE-Bio-PE": {KI: 0.0, description: "Bio-PE self-interaction - perfect compatibility"}
  "LDPE-LDPE": {KI: 0.0, description: "LDPE self-interaction - perfect compatibility"}
  "PP-PP": {KI: 0.0, description: "PP self-interaction - perfect compatibility"}
  "PET-PET": {KI: 0.0, description: "PET self-interaction - perfect compatibility"}
  "PVDC-PVDC": {KI: 0.0, description: "PVDC self-interaction - perfect compatibility"}
  "PA-PA": {KI: 0.0, description: "PA self-interaction - perfect compatibility"}
  "EVOH-EVOH": {KI: 0.0, description: "EVOH self-interaction - perfect compatibility"}
  "PHBV-PHBV": {KI: 0.0, description: "PHBV self-interaction - perfect compatibility"}
  
  # Glycerol interactions (plasticizer effect on water vapor transmission - increases permeability)
  # OPTIMIZED KI VALUES for mixed targets (50% and 200% WVTR increase targets)
  "Glycerol-PLA": {KI: 0.650, description: "Glycerol-PLA: Optimized for 50% WVTR increase target"}
  "Glycerol-PBAT": {KI: 0.650, description: "Glycerol-PBAT: Optimized for 50% WVTR increase target"}
  "Glycerol-PHB": {KI: 0.700, description: "Glycerol-PHB: Optimized for 50% WVTR increase target"}
  "Glycerol-PHBV": {KI: -1.250, description: "Glycerol-PHBV: Optimized for 50% WVTR increase target"}
  "Glycerol-PHBH": {KI: 0.700, description: "Glycerol-PHBH: Optimized for 50% WVTR increase target"}
  "Glycerol-PHAa": {KI: 0.850, description: "Glycerol-PHAa: Optimized for 50% WVTR increase target"}
  "Glycerol-PHAs": {KI: -1.500, description: "Glycerol-PHAs: Optimized for 50% WVTR increase target"}
  "Glycerol-PGA": {KI: 0.700, description: "Glycerol-PGA: Optimized for 50% WVTR increase target"}
  "Glycerol-PBS": {KI: 2.000, description: "Glycerol-PBS: Optimized for 200% WVTR increase target"}
  "Glycerol-PBSA": {KI: 2.000, description: "Glycerol-PBSA: Optimized for 200% WVTR increase target"}
  "Glycerol-PCL": {KI: 0.700, description: "Glycerol-PCL: Optimized for 50% WVTR increase target"}
  "Glycerol-Bio-PE": {KI: 0.0, description: "Glycerol-Bio-PE: Poor compatibility, limited plasticizer effect"}
  "Glycerol-LDPE": {KI: 0.0, description: "Glycerol-LDPE: Moderate compatibility, plasticizer effect increases WVTR"}
  "Glycerol-PP": {KI: 0.0, description: "Glycerol-PP: Poor compatibility, limited plasticizer effect"}
  "Glycerol-PET": {KI: 0.0, description: "Glycerol-PET: Very poor compatibility, limited plasticizer effect"}
  "Glycerol-PVDC": {KI: 0.0, description: "Glycerol-PVDC: Very poor compatibility, limited plasticizer effect"}
  "Glycerol-PA": {KI: 0.0, description: "Glycerol-PA: Poor compatibility, limited plasticizer effect"}
  "Glycerol-EVOH": {KI: 0.0, description: "Glycerol-EVOH: Poor compatibility, limited plasticizer effect"}